import { defineNavBlock, Trait } from "waygraph";
import type { LoginPage } from "../states/checkout.states.js";

// Nav to the login page (/). page.goto lives here, generated by defineNavBlock -
// actions/submit-login.action.block.ts never navigates.
export const NavLoginBlock = defineNavBlock<LoginPage>({
  name: "nav-login",
  description: "Goes to the Swag Labs login page.",
  checkpoint: "LoginPage",
  url: "/",
  verify: [Trait.visible("#login-button")],
});
