import { Engine, start, end, withTitle } from "waygraph";
import { NavLoginBlock } from "../blocks/nav-login.block.js";
import { SubmitLoginActionBlock } from "../blocks/actions/submit-login.action.block.js";
import { AddToCartBlock } from "../blocks/actions/add-to-cart.action.block.js";
import { CheckoutInfoBlock } from "../blocks/actions/checkout-info.action.block.js";
import { FinishOrderBlock } from "../blocks/actions/finish-order.action.block.js";

const engine = new Engine();

// This is it - a whole real waygraph Flow, five Blocks wide, generated by
// `waygraph try` but otherwise no different from a Flow you'd hand-write:
// nav-* Blocks (defineNavBlock) navigate, action-* Blocks (defineBlock) do
// everything else, connect() (here, defineFlow's own array form) chains
// them into one typed graph, each Block's own Trait verify confirms it
// actually landed where it says it did.
export const quickstartFlow = withTitle(
  engine.defineFlow([start, NavLoginBlock, SubmitLoginActionBlock, AddToCartBlock, CheckoutInfoBlock, FinishOrderBlock, end]),
  "waygraph quickstart - swag labs demo",
);
