export type { Checkpoint, Instruction, Block, DefinedBlock, Start, WaygraphInstanceOption } from "./types.js";
export { connect, checkpoint } from "./types.js";
export { MemKey, MemPage, key, keyGroup } from "./mem-page.js";
export { Trait, urlMatches, textEquals, visible, frameVisible, frameTextEquals, frameContainsText } from "./trait.js";
export {
  runGraph,
  spawnTab,
  narrate,
  Engine,
  start,
  end,
  branch,
  withVerify,
  modVerify,
  modVerifyAll,
  defineBlock,
  defineNavBlock,
  defineNavClickBlock,
  defineMethodBlock,
  defineActionBlock,
  defineAssertBlock,
  definePageBlock,
  defineEffectBlock,
  defineMemEffectBlock,
  defineMemNavBlock,
  locate,
  composeBlock,
  fastForwardComposeBlock,
  isFastForwardBlock,
  preflight,
  withSessionReset,
  withTitle,
  withDemoPace,
  withBlockPace,
  withHighlightStyle,
  withExpectedFailure,
  withHighlightFixtures,
  withStubBefore,
  withStubAfter,
  withStubOnError,
  chainFlow,
  defineLayout,
  map,
  MapBuilder,
} from "./engine.js";
export {
  resolveHighlightSlots,
  resolveSlides,
  runStubPhase,
  resolveFixtureDwellMs,
  resolveSlideDwellMs,
  formatHighlightCaption,
  hasAuthoredStubAfter,
  hasAuthoredStubOnError,
  normalizeHighlightTone,
  normalizeDemoPace,
  normalizeHighlightSize,
  normalizeHighlightWeight,
  applyHighlightStyleDefaults,
  toneIconPrefix,
  resolveStepDemoPace,
  demoPaceScale,
  demoPaceIsBlitz,
  demoPaceIsFast,
  demoPaceIsSlow,
  demoPaceGateMs,
  formatDemoPaceBadge,
  formatDemoPaceLabel,
  normalizeTodos,
  normalizeTodoPos,
  normalizeTodoStyle,
  buildTodoDock,
  applyTodoPhase,
  advanceTodoDock,
  completeSequentialTodoDock,
  applyDevicePhase,
  resolveDeviceState,
  normalizeDevicePreset,
  normalizeDeviceOrientation,
  applyOrientation,
  orientationFromViewport,
  DEVICE_PRESETS,
  FIXTURE_DURATION_MS_DEFAULT,
  FIXTURE_DURATION_FAST_MS_DEFAULT,
  FIXTURE_DURATION_SLOW_MS_DEFAULT,
  SLIDE_DURATION_MS_DEFAULT,
  SLIDE_DURATION_FAST_MS_DEFAULT,
  WAYGRAPH_RING_CSS,
} from "./highlights.js";
export type {
  WaygraphHighlightStub,
  WaygraphHighlightFixture,
  WaygraphSlide,
  WaygraphTodoItem,
  WaygraphTodoInput,
  WaygraphTodoGroup,
  WaygraphTodoGroupInput,
  WaygraphTodosOpts,
  TodoDockState,
  TodoListStyle,
  FixtureDurationFields,
  HighlightStubPhase,
  HighlightStubPhaseName,
  HighlightFixtureMap,
  ResolvedHighlight,
  WaygraphHighlight,
  HighlightTone,
  HighlightSize,
  HighlightWeight,
  HighlightStyleDefaults,
  DemoPace,
  DemoPaceName,
  StubCtx,
  StubLifecycleFn,
  StubPhaseResult,
  StubPhaseFixtures,
  DevicePreset,
  DeviceViewport,
  DeviceState,
  DeviceOrientation,
} from "./highlights.js";
export type {
  Flow,
  EngineConfig,
  ComposedBlock,
  FastForwardComposedBlock,
  RunGraphOptions,
  BlockInfo,
  NavBlock,
  NavBlockOptions,
  NavClickBlock,
  NavClickBlockOptions,
  MethodBlock,
  ActionBlock,
  AssertBlock,
  AssertBlockOptions,
  PageBlock,
  PageBlockOptions,
  PageMethodEntry,
  EffectBlock,
  MemEffectBlock,
  MemNavBlock,
  Layout,
  LayoutOptions,
  MapBuilderOptions,
} from "./engine.js";
export type { ActionPage } from "./types.js";
export { discoverGraph, toMermaid, findOrphanBlocks, findBlockPath } from "./graph.js";
export type { WaygraphGraph, WaygraphNode, WaygraphEdge, SkippedBlock, OrphanBlock } from "./graph.js";
export {
  isFileSelectToken,
  parseBlocksSelect,
  matchBlocksSelect,
  globToRegExp,
} from "./blocks-select.js";
export type { BlocksSelect, BlocksSelectKind } from "./blocks-select.js";
export { EdgeLeaseCoordinator } from "./traverse-lease.js";
export { runTraverse } from "./traverse-run.js";
export type {
  TraverseOptions,
  TraverseSessionMode,
  TraverseWorkerResult,
} from "./traverse-run.js";
export {
  buildCoverageReport,
  collectGraphEdgeKeys,
  defaultCoverageOutPath,
  formatCoverageLine,
  normalizeHitKey,
  parseMinEdgeCoverage,
  writeCoverageReport,
} from "./traverse-coverage.js";
export type { TraverseCoverageReport } from "./traverse-coverage.js";
export {
  WG_UI_SEL,
  WG_READY_PANEL_SEL,
  WG_READY_AUTO_SEL,
  WG_READY_BANNER_SEL,
  readWgOverlayBeacon,
  readWgOverlayBeaconInPage,
  assertWgOverlayReady,
} from "./overlay-beacon.js";
export type { WgModalKind, WgBeaconRow } from "./overlay-beacon.js";
export { AutoSession, stubFilePath } from "./auto-session.js";
export type {
  AutoSessionInit,
  SessionSnapshot,
  SessionSnapshotEdge,
  SessionSnapshotSection,
  ApplyPickResult,
  ApplyPathResult,
  TraceStep,
  ConsoleLogEntry,
  StorageSnapshot,
  ServiceWorkerRegistrationInfo,
  CookieInfo,
  StubFileKind,
} from "./auto-session.js";
export { pilotStart } from "./pilot.js";
export type { PilotStartResult } from "./pilot.js";
