export type { Checkpoint, Instruction, Block, DefinedBlock, Start, WaygraphInstanceOption } from "./types.js";
export { connect, checkpoint } from "./types.js";
export { MemKey, MemPage, key, keyGroup } from "./mem-page.js";
export { Trait, urlMatches, textEquals, visible } from "./trait.js";
export {
  runGraph,
  spawnTab,
  narrate,
  Engine,
  start,
  end,
  branch,
  withVerify,
  modVerify,
  modVerifyAll,
  defineBlock,
  defineNavBlock,
  defineNavClickBlock,
  defineMethodBlock,
  defineActionBlock,
  definePageBlock,
  defineEffectBlock,
  defineMemEffectBlock,
  defineMemNavBlock,
  locate,
  composeBlock,
  fastForwardComposeBlock,
  isFastForwardBlock,
  preflight,
  withSessionReset,
  withTitle,
  withDemoPace,
  withBlockPace,
  withHighlightStyle,
  withExpectedFailure,
  withHighlightFixtures,
  chainFlow,
} from "./engine.js";
export {
  resolveHighlightSlots,
  resolveSlides,
  resolveFixtureDwellMs,
  resolveSlideDwellMs,
  formatHighlightCaption,
  hasAuthoredStubAfter,
  hasAuthoredStubOnError,
  normalizeHighlightTone,
  normalizeDemoPace,
  normalizeHighlightSize,
  normalizeHighlightWeight,
  applyHighlightStyleDefaults,
  toneIconPrefix,
  resolveStepDemoPace,
  demoPaceScale,
  demoPaceIsBlitz,
  demoPaceIsFast,
  demoPaceIsSlow,
  demoPaceGateMs,
  formatDemoPaceBadge,
  formatDemoPaceLabel,
  FIXTURE_DURATION_MS_DEFAULT,
  FIXTURE_DURATION_FAST_MS_DEFAULT,
  FIXTURE_DURATION_SLOW_MS_DEFAULT,
  SLIDE_DURATION_MS_DEFAULT,
  SLIDE_DURATION_FAST_MS_DEFAULT,
} from "./highlights.js";
export type {
  WaygraphHighlightStub,
  WaygraphHighlightFixture,
  WaygraphSlide,
  FixtureDurationFields,
  HighlightStubPhase,
  HighlightStubPhaseName,
  HighlightFixtureMap,
  ResolvedHighlight,
  WaygraphHighlight,
  HighlightTone,
  HighlightSize,
  HighlightWeight,
  HighlightStyleDefaults,
  DemoPace,
  DemoPaceName,
} from "./highlights.js";
export type {
  Flow,
  EngineConfig,
  ComposedBlock,
  FastForwardComposedBlock,
  RunGraphOptions,
  BlockInfo,
  NavBlock,
  NavBlockOptions,
  NavClickBlock,
  NavClickBlockOptions,
  MethodBlock,
  ActionBlock,
  PageBlock,
  PageBlockOptions,
  PageMethodEntry,
  EffectBlock,
  MemEffectBlock,
  MemNavBlock,
} from "./engine.js";
export type { ActionPage } from "./types.js";
export { discoverGraph, toMermaid, findOrphanBlocks, findBlockPath } from "./graph.js";
export type { WaygraphGraph, WaygraphNode, WaygraphEdge, SkippedBlock, OrphanBlock } from "./graph.js";
export {
  isFileSelectToken,
  parseBlocksSelect,
  matchBlocksSelect,
  globToRegExp,
} from "./blocks-select.js";
export type { BlocksSelect, BlocksSelectKind } from "./blocks-select.js";
export { EdgeLeaseCoordinator } from "./traverse-lease.js";
export { runTraverse } from "./traverse-run.js";
export type { TraverseOptions, TraverseSessionMode } from "./traverse-run.js";
